apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
spec:
  containers:
    - name: python-rmq-test-consumer
      image: marcopaspuel/python-rmq-test:1.0.0
      imagePullPolicy: Always
      args: ["python", "./consumer.py", "--user", "admin", "--password", "brighter-ai", "--host", "ipson-rabbitmq.ipson.svc.cluster.local", "--port", "5672", "--queue", "workers-queue"]
  restartPolicy: Never
