apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-client
        image: jeffhollan/rabbitmq-client:dev
        imagePullPolicy: Always
        command: ["send",  "amqp://admin:brighter-ai@ipson-rabbitmq.ipson-rabbitmq-system.svc.cluster.local:5672", "20"]
      restartPolicy: Never
  backoffLimit: 4
